services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_network
    restart: unless-stopped
networks:
  app_network:
    driver: bridge
