services:
  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"    # Certbot xác thực qua port 80
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot  # Certbot validation
      - ./certbot/conf:/etc/letsencrypt  # Lưu chứng chỉ
    networks:
      - app_network
    depends_on:
      - api

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app_network
    # Lệnh thực sự để tạo chứng chỉ (đã bỏ --dry-run)
    command: certonly --webroot -w /var/www/certbot --email hieupv2412@gmail.com --agree-tos --no-eff-email -d hieupv.site -d www.hieupv.site

networks:
  app_network:
    driver: bridge