// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogPost struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Description string           `json:"description"`
	Content     string           `json:"content"`
	ImageUrl    string           `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Description pgtype.Text      `json:"description"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ContactMessage struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Message   string           `json:"message"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Page struct {
	ID          int32            `json:"id"`
	Slug        string           `json:"slug"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID                int32            `json:"id"`
	CategoryID        int32            `json:"category_id"`
	Name              string           `json:"name"`
	Slug              string           `json:"slug"`
	Description       string           `json:"description"`
	Price             float64          `json:"price"`
	PriceSale         float64          `json:"price_sale"`
	UnitOfMeasurement string           `json:"unit_of_measurement"`
	ImageUrl          string           `json:"image_url"`
	ThumbUrl          string           `json:"thumb_url"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type WebsiteSetting struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}
