// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogPost struct {
	ID        int32
	Title     string
	Content   string
	ImageUrl  pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Category struct {
	ID          int32
	Name        string
	Slug        string
	Description pgtype.Text
	ImageUrl    pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type ContactMessage struct {
	ID        int32
	Name      string
	Email     string
	Message   string
	CreatedAt pgtype.Timestamp
}

type Product struct {
	ID          int32
	CategoryID  int32
	Name        string
	Slug        string
	Description string
	Price       pgtype.Numeric
	PriceSale   pgtype.Numeric
	ImageUrl    string
	ThumbUrl    string
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type WebsiteSetting struct {
	ID    int32
	Name  string
	Value string
}
