// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	// Blog Post Queries
	CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (int32, error)
	// Pages Queries
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateWebsiteSetting(ctx context.Context, arg CreateWebsiteSettingParams) (int32, error)
	DeleteBlogPost(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeletePage(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWebsiteSetting(ctx context.Context, id int32) error
	GetBlogPost(ctx context.Context, id int32) (BlogPost, error)
	GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetPage(ctx context.Context, id int32) (Page, error)
	GetPageBySlug(ctx context.Context, slug string) (Page, error)
	GetProduct(ctx context.Context, id int32) (GetProductRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetTotalBlogPosts(ctx context.Context) (int64, error)
	GetTotalPages(ctx context.Context) (int64, error)
	GetTotalProducts(ctx context.Context) (int64, error)
	GetTotalProductsByCategoryID(ctx context.Context, id int32) (int64, error)
	GetTotalProductsByCategorySlug(ctx context.Context, slug string) (int64, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCount(ctx context.Context) (int64, error)
	GetWebsiteSetting(ctx context.Context, id int32) (WebsiteSetting, error)
	GetWebsiteSettingByName(ctx context.Context, name string) (WebsiteSetting, error)
	ListBlogPosts(ctx context.Context, arg ListBlogPostsParams) ([]BlogPost, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error)
	ListProductsByCategoryID(ctx context.Context, arg ListProductsByCategoryIDParams) ([]ListProductsByCategoryIDRow, error)
	ListProductsByCategorySlug(ctx context.Context, arg ListProductsByCategorySlugParams) ([]ListProductsByCategorySlugRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListWebsiteSettings(ctx context.Context) ([]WebsiteSetting, error)
	SearchBlogPosts(ctx context.Context, arg SearchBlogPostsParams) ([]BlogPost, error)
	UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWebsiteSetting(ctx context.Context, arg UpdateWebsiteSettingParams) error
}

var _ Querier = (*Queries)(nil)
