// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type BlogPost struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ContactMessage struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Product struct {
	ID          int32          `json:"id"`
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImageUrl    sql.NullString `json:"image_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type ProductCategory struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type WebsiteSetting struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}
